spring.application.name=amazon-scale-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/amazon_db
spring.datasource.username=Amit
spring.datasource.password=Amazon@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true